### ISSUE TITLE
HCP subjects IDs

### ISSUE THREAD

**Issue by pietroastolfi** [SlicerDMRI/ORG-Atlases#2]
Hi,

is there available a list of the 100 HCP subjects IDs?

Thanks

**Comment by zhangfanmark** [comment]
> Hi,
> 
> 
> 
> is there available a list of the 100 HCP subjects IDs?
> 
> 
> 
> Thanks 

Hi,

It is the Unrelated100subjects. You can download the list from the HCP database.

Regards,
Fan

**Comment by pietroastolfi** [comment]
Found, thanks.
