### ISSUE TITLE
Discrepancy in CPC labeling in atlas and whitematteranalysis code

### ISSUE THREAD

**Issue by josephmje** [SlicerDMRI/ORG-Atlases#3]
Hi there,

I was wondering whether the CPC is considered to be a commissural tract in the atlas or whether it should be hemispheric?
The whitematteranalysis results output both left and right tracts as a single file.

Thank you!

**Comment by zhangfanmark** [comment]
Hi, CPC should be hemispheric. We have updated the WMA code to separate CPC so there should now be two separated files for CPC. Please let us know if that works for you. Thank you for opening this issue here!

Regards,
Fan
